// Audience landing pages, built to /for/<slug>/ by scripts/build-blog.mjs.
// Facts only: real projects, the real verified review, timelines in weeks, no prices.

export const REVIEW = {
  quote: "Well-architected, purpose-driven, and executionally clean: a strong example of niche EdTech done right.",
  name: "Elena Marisol Hikida",
  role: "Founder & CEO, HiKIDAI",
  badge: "Verified client",
};

export const landingPages = [
  {
    slug: "agencies",
    need: "crm",
    nav: "Agencies",
    eyebrow: "For agencies & service businesses",
    title: "A custom CRM that fits how your agency actually works",
    seoTitle: "Custom CRM for Agencies & Service Businesses",
    description: "Stop juggling spreadsheets, inboxes and five subscriptions. A custom CRM built around your agency's pipeline, clients and team, and you own it.",
    sub: "Leads in one inbox, projects in another tool, invoices in a spreadsheet, and the \"real\" status in someone's head. I design and build a CRM around your pipeline, so your team sees every client, deal and follow-up in one place.",
    prefill: "Hi Vincent, I run an agency / service business and I'm interested in a custom CRM.\n\nHow we track clients today:\n\nTeam size:\n\nWhat I'd like to fix first:\n",
    pains: [
      { title: "Follow-ups fall through the cracks", body: "A lead goes quiet, nobody chases it, and a competitor lands the deal." },
      { title: "You pay for seats and features you don't use", body: "Every new hire adds another license, and the tool still doesn't match your process." },
      { title: "Status lives in five places", body: "Sales, delivery and billing each have their own tool, and someone copies data between them by hand." },
    ],
    build: [
      { icon: "view_kanban", title: "Your pipeline, your stages", body: "Boards that match how you sell and deliver, from inquiry to signed to invoiced." },
      { icon: "contacts", title: "Client & contact records", body: "Every call, email, file and deal for a client on one page." },
      { icon: "notifications_active", title: "Automatic follow-ups", body: "Reminders and tasks that assign themselves, so no lead goes cold." },
      { icon: "monitoring", title: "Dashboards that answer questions", body: "Pipeline value, win rate, workload per person, at a glance." },
      { icon: "admin_panel_settings", title: "Roles & permissions", body: "Everyone sees what they need, and client data stays protected." },
      { icon: "hub", title: "Connected to your tools", body: "Email, calendar, forms on your website, invoicing and more." },
    ],
    demo: {
      type: "link",
      title: "See a team operations dashboard",
      body: "TS Task Control shows the kind of screen I build for service teams: each person's workload, a live pipeline of client work, and a review screen that flags problems before clients notice.",
      image: "/projects/ts-task-control.jpg",
      url: "https://ts-task-control-ui.vercel.app/",
      cta: "Open the prototype",
      note: "Design prototype. A private CRM walkthrough is available on request.",
    },
    projects: [
      { title: "Harbor Reach Studio OS", label: "Client work · design", body: "A calm operating system for a five-person studio: milestones, department progress, risks and reviews in one view.", url: "https://harbor-reach-studio-os-ui.vercel.app/" },
      { title: "CRM System", label: "In development", body: "A custom CRM for contacts, deals and follow-ups. Ask for a private walkthrough.", url: "/#contact" },
    ],
    timeline: "6–12 weeks",
    faq: [
      { q: "Should my agency just use HubSpot or Pipedrive?", a: "Often, yes, at first, and I'll tell you if that's the better fit. Custom makes sense when you're bending your process to fit the tool, paying for many unused seats, or need the CRM tightly connected to your own systems." },
      { q: "Can you import our spreadsheets and existing CRM data?", a: "Yes. I map your fields, clean duplicates and import contacts, deals and history as part of the project." },
      { q: "Who owns the CRM when it's done?", a: "You do: the code, the database and every account are in your name." },
      { q: "How long does a custom CRM take?", a: "Most agency CRMs take 6–12 weeks, split into milestones so your team can start using the core pipeline early." },
    ],
    articles: ["best-crm-software-for-small-business", "how-much-does-a-custom-crm-cost", "spreadsheets-vs-crm-signs-you-outgrew-excel"],
  },
  {
    slug: "clinics-salons",
    need: "booking",
    nav: "Clinics & salons",
    eyebrow: "For clinics, salons & studios",
    title: "Online booking that fills your calendar, even at 9 PM",
    seoTitle: "Online Booking System for Clinics, Salons & Studios",
    description: "Let clients book themselves 24/7 with real-time availability, deposits and SMS reminders, on your own website. Custom booking systems for clinics, salons and studios.",
    sub: "Clients want to book when they're free: evenings, weekends, between meetings. If your only option is \"call us during opening hours\", they book somewhere else. I build booking that lives on your site, follows your rules, and cuts no-shows.",
    prefill: "Hi Vincent, I run a clinic / salon / studio and I'm interested in online booking.\n\nHow clients book today:\n\nNumber of staff / rooms:\n\nWhat I'd like to fix first (no-shows, double bookings, phone calls…):\n",
    pains: [
      { title: "Bookings only during opening hours", body: "Every missed evening call is a client who booked with someone else." },
      { title: "No-shows eat your week", body: "Without reminders or deposits, empty slots cost you money every single week." },
      { title: "Double bookings and paper calendars", body: "Staff, rooms and equipment tracked in different places, and mistakes land on your clients." },
    ],
    build: [
      { icon: "event_available", title: "Real-time availability", body: "Staff, rooms, service lengths and buffers, calculated live." },
      { icon: "payments", title: "Deposits & payments", body: "Take a deposit or full payment at booking to protect your time." },
      { icon: "sms", title: "Email & SMS reminders", body: "Automatic confirmations and reminders that cut no-shows." },
      { icon: "calendar_month", title: "Calendar sync", body: "Two-way sync with Google and Outlook, so no double bookings." },
      { icon: "dashboard", title: "Front-desk dashboard", body: "Today's bookings, reschedules and client history in one screen." },
      { icon: "brush", title: "Your brand, your website", body: "Booking lives on your site, not on a third-party page." },
    ],
    demo: {
      type: "booking",
      title: "Try it: book a sample appointment",
      body: "This is a working sample of the booking flow your clients would use. Pick a service, a day and a time. Nothing is actually booked.",
      note: "Interactive sample. No real booking or payment is made.",
    },
    projects: [
      { title: "Best Online Booking Software (2026)", label: "Guide", body: "Calendly, Acuity, Setmore, SimplyBook.me and Cal.com compared with real prices, useful if an off-the-shelf tool is enough for now.", url: "/blog/best-online-booking-software/" },
      { title: "HiKIDAI", label: "Client project", body: "A live learning platform with a CMS, database and auth backend. Built end to end, reviewed by its founder.", url: "#proof" },
    ],
    timeline: "4–8 weeks",
    faq: [
      { q: "Should I just use Calendly, Acuity or Setmore?", a: "If a standard tool fits your rules, start there, and I'll say so. Custom booking makes sense when your rules are unusual (rooms, equipment, packages), when booking must live inside your own site or app, or when it needs to connect to your CRM." },
      { q: "Can clients pay a deposit when they book?", a: "Yes. I integrate payment providers like Stripe for deposits, full payments and refunds." },
      { q: "Will it work on phones?", a: "Yes. It's designed mobile-first, because that's where most clients book." },
      { q: "How long does it take?", a: "Most booking systems take 4–8 weeks, depending on your rules and integrations." },
    ],
    articles: ["best-online-booking-software", "online-booking-system-guide", "what-to-prepare-before-hiring-a-developer"],
  },
  {
    slug: "saas-web3",
    need: "dashboard",
    nav: "SaaS & Web3",
    eyebrow: "For SaaS & Web3 teams",
    title: "Dashboards your team actually understands",
    seoTitle: "Custom Dashboards & Admin Panels for SaaS and Web3 Teams",
    description: "Custom operations dashboards, admin panels and control rooms for SaaS and Web3 teams: live data, clear alerts and actions in one screen. See a live demo.",
    sub: "Your data lives in Datadog, your database, the chain and three admin tools. I design and build one control room around your product: live health, the jobs and customers that matter, and the actions your team takes every day.",
    prefill: "Hi Vincent, I'm on a SaaS / Web3 team and I'm interested in a custom dashboard or admin panel.\n\nWhat we monitor today (tools):\n\nWho would use it:\n\nThe one screen I wish we had:\n",
    pains: [
      { title: "Five tabs to answer one question", body: "Metrics in one tool, logs in another, customers in the database, and on-chain data somewhere else." },
      { title: "Generic tools don't speak your language", body: "CPU graphs are useful, but your team thinks in jobs, customers, transactions and incidents." },
      { title: "Admin work happens in raw SQL", body: "Refunds, retries and fixes are done by hand in the database, which is slow and risky." },
    ],
    build: [
      { icon: "speed", title: "Live health & KPIs", body: "Latency, errors, throughput and your business metrics in one view." },
      { icon: "account_tree", title: "Service & dependency maps", body: "See what depends on what, and where a problem really starts." },
      { icon: "terminal", title: "Logs, traces & incidents", body: "Streaming logs with filters, traces and incident workflows." },
      { icon: "bolt", title: "Actions, not just charts", body: "Retry jobs, resolve incidents, trigger deploys, with the right permissions." },
      { icon: "token", title: "Web3-ready", body: "Wallet connection, on-chain data and multichain RPC with fallbacks." },
      { icon: "palette", title: "Branded & shareable", body: "Your name, colors and environments, for your team or your customers." },
    ],
    demo: {
      type: "link",
      title: "Click through a live control room",
      body: "Obsidian Console is a working observability console for a Web3 compute platform: live service health, telemetry charts, a streaming log viewer, TEE job orchestration, incident response and ⌘K search. You can even rebrand it from its settings page.",
      image: "/projects/obsidian-console.jpg",
      url: "https://obsidian-console-eosin.vercel.app/",
      cta: "Open the live demo",
      note: "Concept with simulated data. For your team, it would connect to your real data sources.",
    },
    projects: [
      { title: "RemitOtter", label: "Live demo · Web3", body: "A Solana token platform with a real-time dashboard, a public ledger and a partner API. 20 API routes plus a test suite.", url: "https://solana-meme-bank.preview.emergentagent.com" },
      { title: "This portfolio", label: "Web3 · live", body: "Live data from 7 chains (6 EVM plus Solana) with automatic RPC fallback, and read-only wallet connection.", url: "/#web3" },
    ],
    timeline: "4–10 weeks",
    faq: [
      { q: "Does a custom dashboard replace Datadog or Grafana?", a: "No. It usually sits on top of them, using them as data sources, and adds your business context and actions in one place." },
      { q: "Can it connect to our database and on-chain data?", a: "Yes. Dashboards can read from your database, monitoring APIs, chain RPCs and indexers, with read-only access where that's safer." },
      { q: "Who can see and do what?", a: "Roles and permissions control which screens and actions each person has, and actions can be logged for auditing." },
      { q: "How long does it take?", a: "Most dashboards and admin panels take 4–10 weeks, starting with the one screen your team needs most." },
    ],
    articles: ["best-monitoring-tools-for-startups", "supabase-vs-firebase-for-your-mvp", "website-vs-web-app-vs-mobile-app"],
  },
];
